
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/1054626.crt:/etc/nginx/ssl/1054626.crt
      - ./certs/1054626.key:/etc/nginx/ssl/1054626.key
    depends_on:
      - chat-backend
    networks:
      - chat-network

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-broker
    ports:
      - 1883:1883
      - 1884:1884
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/passwordfile:/mosquitto/config/passwordfile
      - ./certs/1054626.crt:/mosquitto/config/1054626.crt
      - ./certs/1054626.key:/mosquitto/config/1054626.key
    networks:
      - chat-network

  chat-backend:
    build: ./backend
    container_name: chat-backend
    depends_on:
      - mosquitto
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
